name: Documentation request
description: Create a report about a missing documentation
title: ""
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this document request!
  - type: textarea
    id: missing-doc
    attributes:
      label: Describe the missing documentation
      description: Which part of the documentation is missing?
      placeholder: Describe the issue with a part of the documentation (missing, unclear, at the wrong place).
    validations:
      required: true
