name: Feature request
description: Suggest an idea for this project
title: "\U0001F680 "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-request
    attributes:
      label: What problem does this feature solve?
      description: Is your feature request related to a problem? Please describe.
      placeholder: Describe the problem you are experiencing or what improvement you would like to see.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Solution?
      description: Describe the proposed solution.
    validations:
      required: false
