name: compare-the-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - uses: iterative/setup-cml@v1
        with: 
          version: latest
        
      - name: cml_run
        run: |
          conda env create -f environment.yml
