name: train-my-model
on: [push]
jobs:
  run:
     runs-on: [ubuntu-latest]
     container: docker://dvcorg/cml-py3:latest
     steps:
        - uses: actions/checkout@v2
        - name: cml_run
           env:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
           run: |
              conda env create -f environment.yml
